version: '3.8'

# =============================================================================
# 最简自动追番服务 Docker Compose 配置
# 支持 RSS 订阅和自动下载动漫番剧
# =============================================================================

networks:
  anime-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

services:
  # =============================================================================
  # qBittorrent - 下载器（带 RSS 支持）
  # =============================================================================
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: anime-qbittorrent
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Asia/Shanghai}
      - UMASK=022
      - WEBUI_PORT=8080
    volumes:
      - ${CONFIG_PATH}/anime-qbittorrent:/config
      - ${DOWNLOAD_PATH}/anime:/downloads
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    networks:
      anime-network:
        ipv4_address: 172.21.0.10
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # =============================================================================
  # FlexGet - 自动化下载工具（支持 RSS）
  # =============================================================================
  flexget:
    image: cpoppema/docker-flexget:latest
    container_name: anime-flexget
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Asia/Shanghai}
      - FG_WEBUI_PASS=${FLEXGET_WEBUI_PASS:-password123}
    volumes:
      - ${CONFIG_PATH}/anime-flexget:/config
      - ${DOWNLOAD_PATH}/anime:/downloads
    ports:
      - "5050:5050"
    networks:
      anime-network:
        ipv4_address: 172.21.0.11
    depends_on:
      - qbittorrent
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s