# =============================================================================
# Homepage 导航页配置
# =============================================================================

services:
  - 核心服务:
      - MoviePilot:
          icon: moviepilot.png
          href: http://{{HOMEPAGE_VAR_HOST}}:8001
          description: 影视自动化管理
          ping: http://{{HOMEPAGE_VAR_HOST}}:8001
          widget:
            type: moviepilot
            url: http://{{HOMEPAGE_VAR_HOST}}:8001
            key: {{HOMEPAGE_VAR_MOVIEPILOT_API_KEY}}

      - Emby:
          icon: emby.png
          href: http://{{HOMEPAGE_VAR_HOST}}:8096
          description: 媒体服务器
          ping: http://{{HOMEPAGE_VAR_HOST}}:8096
          widget:
            type: emby
            url: http://{{HOMEPAGE_VAR_HOST}}:8096
            key: {{HOMEPAGE_VAR_EMBY_API_KEY}}

      - qBittorrent:
          icon: qbittorrent.png
          href: http://{{HOMEPAGE_VAR_HOST}}:8080
          description: 主力下载器
          ping: http://{{HOMEPAGE_VAR_HOST}}:8080
          widget:
            type: qbittorrent
            url: http://{{HOMEPAGE_VAR_HOST}}:8080
            username: {{HOMEPAGE_VAR_QB_USERNAME}}
            password: {{HOMEPAGE_VAR_QB_PASSWORD}}

      - Transmission:
          icon: transmission.png
          href: http://{{HOMEPAGE_VAR_HOST}}:9091
          description: 保种下载器
          ping: http://{{HOMEPAGE_VAR_HOST}}:9091
          widget:
            type: transmission
            url: http://{{HOMEPAGE_VAR_HOST}}:9091
            username: {{HOMEPAGE_VAR_TR_USERNAME}}
            password: {{HOMEPAGE_VAR_TR_PASSWORD}}

  - 媒体库:
      - Komga:
          icon: komga.png
          href: http://{{HOMEPAGE_VAR_HOST}}:25600
          description: 漫画服务器
          ping: http://{{HOMEPAGE_VAR_HOST}}:25600

      - Audiobookshelf:
          icon: audiobookshelf.png
          href: http://{{HOMEPAGE_VAR_HOST}}:25378
          description: 有声书服务器
          ping: http://{{HOMEPAGE_VAR_HOST}}:25378

      - Navidrome:
          icon: navidrome.png
          href: http://{{HOMEPAGE_VAR_HOST}}:25533
          description: 音乐服务器
          ping: http://{{HOMEPAGE_VAR_HOST}}:25533

      - Calibre:
          icon: calibre.png
          href: http://{{HOMEPAGE_VAR_HOST}}:8083
          description: 电子书管理
          ping: http://{{HOMEPAGE_VAR_HOST}}:8083

      - Reader:
          icon: reader.png
          href: http://{{HOMEPAGE_VAR_HOST}}:8082
          description: 小说阅读
          ping: http://{{HOMEPAGE_VAR_HOST}}:8082

  - 工具服务:
      - CookieCloud:
          icon: cookiecloud.png
          href: http://{{HOMEPAGE_VAR_HOST}}:8088
          description: Cookie同步
          ping: http://{{HOMEPAGE_VAR_HOST}}:8088

      - ChineseSubFinder:
          icon: chinesesubfinder.png
          href: http://{{HOMEPAGE_VAR_HOST}}:19035
          description: 中文字幕下载
          ping: http://{{HOMEPAGE_VAR_HOST}}:19035

      - IYUU:
          icon: iyuu.png
          href: http://{{HOMEPAGE_VAR_HOST}}:9780
          description: 自动辅种
          ping: http://{{HOMEPAGE_VAR_HOST}}:9780

      - Vertex:
          icon: vertex.png
          href: http://{{HOMEPAGE_VAR_HOST}}:3030
          description: PT刷流工具
          ping: http://{{HOMEPAGE_VAR_HOST}}:3030

      - FreshRSS:
          icon: freshrss.png
          href: http://{{HOMEPAGE_VAR_HOST}}:8084
          description: RSS阅读器
          ping: http://{{HOMEPAGE_VAR_HOST}}:8084

      - Metube:
          icon: metube.png
          href: http://{{HOMEPAGE_VAR_HOST}}:8081
          description: 视频下载
          ping: http://{{HOMEPAGE_VAR_HOST}}:8081

widgets:
  - resources:
      cpu: true
      memory: true
      disk: /
      cputemp: true
      uptime: true

  - search:
      provider: google
      target: _blank

  - datetime:
      text_size: xl
      format:
        dateStyle: long
        timeStyle: medium
        hour12: false

bookmarks:
  - 开发资源:
      - GitHub:
          - icon: github.png
            href: https://github.com/
      - Docker Hub:
          - icon: docker.png
            href: https://hub.docker.com/

  - 常用网站:
      - PT站点:
          - href: https://example-pt-site.com
            description: 示例PT站点
      - 影视资讯:
          - href: https://www.imdb.com
            description: IMDB