# =============================================================================
# Homepage 设置配置
# =============================================================================

title: NAS 自动化影音管理中心
background: https://images.unsplash.com/photo-1518709268805-4e9042af2176?auto=format&fit=crop&w=1920&q=80
theme: dark
color: slate
target: _blank
hideVersion: true
hideErrors: false

# 布局配置
layout:
  核心服务:
    style: row
    columns: 4
  媒体库:
    style: row  
    columns: 5
  工具服务:
    style: row
    columns: 6

# 语言设置
language: zh-CN

# 首页选项
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  hideVisitURL: false

# 状态样式
statusStyle: "dot"

# 图标配置
iconStyle: theme

# 搜索配置
search:
  provider: google
  target: _blank

# 页脚配置
footer: false