# =============================================================================
# Homepage Widget 配置
# =============================================================================

# 系统资源监控
- resources:
    cpu: true
    memory: true
    disk: /opt/nas-data
    cputemp: true
    uptime: true
    units: metric
    refresh: 3000

# 网络监控
- resources:
    label: 网络
    expanded: false
    tx: 
    rx:

# 搜索框
- search:
    provider: [google, duckduckgo, bing]
    target: _blank

# 时间显示
- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: medium
      hour12: false

# Docker 容器状态
- docker:
    socket: /var/run/docker.sock
    showStats: true

# 天气信息（可选）
# - openweathermap:
#     label: 天气
#     latitude: 39.9042
#     longitude: 116.4074
#     units: metric
#     apikey: your_openweather_api_key
#     cache: 5

# 自定义信息
- greeting:
    text: 欢迎使用 NAS 自动化影音管理系统
    text_size: xl

# 快速链接
- quicklaunch:
    searchDescriptions: true
    hideInternetSearch: false
    hideVisitURL: false