# =============================================================================
# MoviePilot 配置文件模板
# =============================================================================

# 基础配置
app:
  # 应用名称
  app_name: "MoviePilot"
  # 调试模式
  debug: false
  # 日志级别
  log_level: "INFO"
  # 时区
  timezone: "Asia/Shanghai"

# 安全配置
security:
  # 超级用户配置
  superuser: "admin"
  superuser_password: "password123"
  # API令牌
  api_token: "your_api_token_here"
  # 会话超时时间（分钟）
  session_timeout: 720

# 媒体库配置
media:
  # 媒体根目录  
  movie_path: "/media/movies"
  tv_path: "/media/tv"
  anime_path: "/media/anime"
  # 分类配置
  category:
    movie:
      - "电影"
      - "纪录片"
    tv:
      - "电视剧"
      - "综艺"
    anime:
      - "动漫"

# 下载器配置
downloaders:
  # qBittorrent配置
  qbittorrent:
    enable: true
    host: "qbittorrent"
    port: 8080
    username: "admin"
    password: "adminpass"
    # 下载目录映射
    download_dir: "/downloads/complete"
    # 分类设置
    category: true
  
  # Transmission配置
  transmission:
    enable: true
    host: "transmission"
    port: 9091
    username: "admin"
    password: "password123"

# 媒体服务器配置
mediaservers:
  # Emby配置
  emby:
    enable: true
    host: "emby"
    port: 8096
    api_key: "your_emby_api_key_here"
    # 媒体库ID映射
    libraries:
      movie: "1"
      tv: "2"
      anime: "3"

# 索引器配置
indexers:
  # 内置索引器
  builtin:
    enable: true
  # 自定义索引器
  prowlarr:
    enable: false
    host: ""
    port: 9696
    api_key: ""

# 识别配置
recognize:
  # TMDB配置
  tmdb:
    api_key: "your_tmdb_api_key"
    language: "zh-CN"
  
  # 豆瓣配置  
  douban:
    enable: true

# 刮削器配置
scraper:
  # 电影刮削
  movie:
    - "tmdb"
    - "douban"
  # 电视剧刮削
  tv:
    - "tmdb"
    - "douban"

# 过滤器配置
filter:
  # 文件大小过滤
  size:
    min_size: "1GB"
    max_size: "50GB"
  
  # 质量过滤
  quality:
    include:
      - "1080p"
      - "2160p"
    exclude:
      - "CAM"
      - "TS"
  
  # 制作组过滤
  team:
    include: []
    exclude:
      - "YIFY"

# 通知配置
notification:
  # 微信通知
  wechat:
    enable: false
    corp_id: ""
    corp_secret: ""
    agent_id: ""
  
  # Telegram通知
  telegram:
    enable: false
    bot_token: ""
    chat_id: ""

# 定时任务配置
scheduler:
  # RSS订阅检查
  rss_check: "*/15 * * * *"
  # 媒体库同步
  sync_mediaserver: "0 */6 * * *"
  # 清理任务
  cleanup: "0 2 * * *"

# 代理配置
proxy:
  enable: false
  http: ""
  https: ""
  
# 高级配置
advanced:
  # 大内存模式
  big_memory_mode: true
  # 自动更新
  auto_update: true
  # 开发模式
  dev_mode: false